### ISSUE TITLE
Assembler not working with highcharts 8.0.0

### ISSUE THREAD

**Issue by afont1991** [highcharts/highcharts-assembler#13]
I am attempting to use the highcharts assembler to create a custom bundle. I have noticed it does not work when used as explained in the documents with the newly released version 8.0.0 of highcharts. 

When following the example provided here: https://www.highcharts.com/docs/getting-started/how-to-create-custom-highcharts-files I get the following error:

```
TypeError: Cannot read property 'includes' of null
    at searchCapture (/home/andrew/Code/highcharts-master/node_modules/highcharts-assembler/src/dependencies.js:161:18)
    at getModuleName (/home/andrew/Code/highcharts-master/node_modules/highcharts-assembler/src/dependencies.js:226:5)
    at compileFile (/home/andrew/Code/highcharts-master/node_modules/highcharts-assembler/src/dependencies.js:565:18)
    at getIndividualOptions.forEach (/home/andrew/Code/highcharts-master/node_modules/highcharts-assembler/src/build.js:179:20)
    at Array.forEach (<anonymous>)
    at build (/home/andrew/Code/highcharts-master/node_modules/highcharts-assembler/src/build.js:178:8)
    at Object.<anonymous> (/home/andrew/Code/highcharts-master/custom-line-builder.js:7:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
```

I was able to run my code successfully when downgrading to 7.2.1 , but my team would like to use 8.0.0

**Comment by bre1470** [comment]
Hello @afont1991! Thank you for reporting the issue. We will look into it.

**Comment by bre1470** [comment]
Unfortunately I can not reproduce the issue. Which commits do you use for `highcharts` and `highcharts-assembler`? How does your custom builder look likes?
