### ISSUE TITLE
Error while creating custom Highchart file

### ISSUE THREAD

**Issue by niwsa** [highcharts/highcharts-assembler#6]
I am getting the below error when trying to run custom-builder
```
➜ node custom-builder.js
fs.js:675
  return binding.read(fd, buffer, offset, length, position);
                 ^

Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:675:18)
    at tryReadSync (fs.js:540:20)
    at fs.readFileSync (fs.js:583:19)
    at getFile (/home/xxxx/Development/mastering-dnd/node_modules/highcharts-assembler/src/utilities.js:61:26)
    at getOrderedDependencies (/home/xxxx/Development/mastering-dnd/node_modules/highcharts-assembler/src/dependencies.js:202:19)
    at imports.reduce (/home/xxxx/Development/mastering-dnd/node_modules/highcharts-assembler/src/dependencies.js:220:13)
    at Array.reduce (<anonymous>)
    at getOrderedDependencies (/home/xxxx/Development/mastering-dnd/node_modules/highcharts-assembler/src/dependencies.js:216:18)
    at compileFile (/home/xxxx/Development/mastering-dnd/node_modules/highcharts-assembler/src/dependencies.js:503:24)
    at getIndividualOptions.forEach (/home/xxxx/Development/mastering-dnd/node_modules/highcharts-assembler/src/build.js:129:26)
```

**Comment by KacperMadej** [comment]
Hi @niwsa 

Thank you for reporting about the problem.

Please add info about your environment - OS, NodeJS version, NPM version (or if not used, version of used by you node modules loader)

**Comment by niwsa** [comment]
➜ cat /etc/issue
Ubuntu 16.04.5 LTS \n \l
➜ node -v
v8.12.0
➜ npm -v
5.5.1
➜ yarn -v (Using yarn to install packages)
1.12.3

custom-builder.js
```
/**
 * Assembler is installed as an NPM package.
 * See "Install the Highcharts assembler" for more information.
 */
const build = require("highcharts-assembler");
build({
  base: "./highcharts/js/masters/",
  files: ["custom.src.js"],
  output: "./dist/"
});
```
custom.src.js
```
import Highcharts from "../parts/Globals.js";
import "../parts/SvgRenderer.js";
import "../parts/Chart.js";
import "../parts/Series.js";
import "../parts/Interaction.js";
import "../modules/data.src.js";
export default Highcharts;
```
